// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(c, a, b) {
    var e = jQuery,
        g = e(this),
        d = e(".ws_list", b),
        h = {
            position: "absolute",
            left: 0,
            top: 0,
            width: "100%",
            height: "100%",
            maxHeight: "none",
            maxWidth: "none",
            transform: "translate3d(0,0,0)"
        },
        f = e("<div>").addClass("ws_effect ws_fade").css(h).css("overflow", "hidden").appendTo(b);
    this.go = function(i, j) {
        var k = e(a.get(i)),
            m = {
                width: k.width(),
                height: k.height()
            };
        k = k.clone().css(h).css(m).hide().appendTo(f);
        if (!c.noCross) {
            var l = e(a.get(j)).clone().css(h).css(m).appendTo(f);
            l.fadeOut(c.duration, function() {
                l.remove()
            })
        }
        k.fadeIn(c.duration, function() {
            g.trigger("effectEnd");
            k.remove()
        })
    }
}; // -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({
    effect: "fade",
    prev: "",
    next: "",
    duration: 20 * 100,
    delay: 37 * 100,
    width: 760,
    height: 720,
    autoPlay: true,
    autoPlayVideo: false,
    playPause: true,
    stopOnHover: true,
    loop: false,
    bullets: 0,
    caption: false,
    captionEffect: "parallax",
    controls: true,
    responsive: 2,
    fullScreen: false,
    gestures: 2,
    onBeforeStep: 0,
    images: [{
        src: "./villagearki_14_pop.jpg",
        title: "Lorem Ipsum",
        descr: "Dolor lorem ipsum"
    }, {
        src: "./villagearki_15_pop.jpg",
        title: "villagearki_15_pop"
    }, {
        src: "./villagearki_16_pop.jpg",
        title: "villagearki_16_pop"
    }, {
        src: "./villagearki_17_pop.jpg",
        title: "villagearki_17_pop"
    }, {
        src: "./villagearki_18_pop.jpg",
        title: "villagearki_18_pop"
    }, {
        src: "./villagearki_19_pop.jpg",
        title: "villagearki_19_pop"
    }, {
        src: "./villagearki_20_pop.jpg",
        title: "villagearki_20_pop"
    }, {
        src: "./villagearki_21_pop.jpg",
        title: "villagearki_21_pop"
    }, {
        src: "./villagearki_22_pop.jpg",
        title: "villagearki_22_pop"
   
    }]
});